/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AuthenticationService } from "../authentication.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AuthenticationCreateInput } from "./AuthenticationCreateInput";
import { Authentication } from "./Authentication";
import { AuthenticationFindManyArgs } from "./AuthenticationFindManyArgs";
import { AuthenticationWhereUniqueInput } from "./AuthenticationWhereUniqueInput";
import { AuthenticationUpdateInput } from "./AuthenticationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AuthenticationControllerBase {
  constructor(
    protected readonly service: AuthenticationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Authentication })
  @nestAccessControl.UseRoles({
    resource: "Authentication",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAuthentication(
    @common.Body() data: AuthenticationCreateInput
  ): Promise<Authentication> {
    return await this.service.createAuthentication({
      data: data,
      select: {
        createdAt: true,
        id: true,
        token: true,
        updatedAt: true,
        validUntil: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Authentication] })
  @ApiNestedQuery(AuthenticationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Authentication",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async authentications(
    @common.Req() request: Request
  ): Promise<Authentication[]> {
    const args = plainToClass(AuthenticationFindManyArgs, request.query);
    return this.service.authentications({
      ...args,
      select: {
        createdAt: true,
        id: true,
        token: true,
        updatedAt: true,
        validUntil: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Authentication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Authentication",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async authentication(
    @common.Param() params: AuthenticationWhereUniqueInput
  ): Promise<Authentication | null> {
    const result = await this.service.authentication({
      where: params,
      select: {
        createdAt: true,
        id: true,
        token: true,
        updatedAt: true,
        validUntil: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Authentication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Authentication",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAuthentication(
    @common.Param() params: AuthenticationWhereUniqueInput,
    @common.Body() data: AuthenticationUpdateInput
  ): Promise<Authentication | null> {
    try {
      return await this.service.updateAuthentication({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          token: true,
          updatedAt: true,
          validUntil: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Authentication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Authentication",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAuthentication(
    @common.Param() params: AuthenticationWhereUniqueInput
  ): Promise<Authentication | null> {
    try {
      return await this.service.deleteAuthentication({
        where: params,
        select: {
          createdAt: true,
          id: true,
          token: true,
          updatedAt: true,
          validUntil: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
